### ISSUE TITLE
My-portfolio peer issues suggestion 

### ISSUE THREAD

**Issue by Abbas-Aljuaifari** [Yonashenok/My-portfolio#3]
We have walked through the code and Yonas work looks clean and well-made.

additional comments and suggestions!!

- The `Ul` has to be inside the footer section and you need to watch your indentation.
- It would be more efficient to read your code if you would add a  comment to your sections and blocks of code.

![Bravo My Man](https://media.giphy.com/media/kdQuvu0LtCEjxYgTcS/giphy.gif)

**Comment by Yonashenok** [comment]
### Thanks for your feedback guys 
*   I have fixed all the issues 

![](https://media.giphy.com/media/l2R0eYcNq9rJUsVAA/giphy.gif)
